### ISSUE TITLE
The public variable autoCommit is readonly

### ISSUE THREAD

**Issue by groovy21** [Bigous/typed-oracledb#2]
The public variable autoCommit at the global level of the oracledb node package can be modified in javascript as per Oracle's documentation and their own tests. But if you try to do it in typescript using these typings the variable cannot be modified. See sample code below

```
import * as OracleDb from "oracledb";
OracleDb.autoCommit = true; // error: [ts] Cannot assign to 'autoCommit' because it is a read-only property. [2540]
```

**Comment by Bigous** [comment]
Hi @groovy21 , please use the [DefintelyTyped]() instead of mine directly. Here and there the latest supported version of oracledb is 1.11.
Using typescript greater than 2.2, you should not need a .d.ts file to have the lint if the javascript is well documented with jsdoc style. So, maintain this repository got pointless. The hole history can be seen at oracle/node-oracledb#169.
Any PR should be sent to DefinitelyTyped.
